//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendPolicy) DeepCopyInto(out *AgentgatewayBackendPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendPolicy.
func (in *AgentgatewayBackendPolicy) DeepCopy() *AgentgatewayBackendPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignmentReference) DeepCopyInto(out *AssignmentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignmentReference.
func (in *AssignmentReference) DeepCopy() *AssignmentReference {
	if in == nil {
		return nil
	}
	out := new(AssignmentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBundle) DeepCopyInto(out *CapabilityBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBundle.
func (in *CapabilityBundle) DeepCopy() *CapabilityBundle {
	if in == nil {
		return nil
	}
	out := new(CapabilityBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBundleList) DeepCopyInto(out *CapabilityBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapabilityBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBundleList.
func (in *CapabilityBundleList) DeepCopy() *CapabilityBundleList {
	if in == nil {
		return nil
	}
	out := new(CapabilityBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBundleReference) DeepCopyInto(out *CapabilityBundleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBundleReference.
func (in *CapabilityBundleReference) DeepCopy() *CapabilityBundleReference {
	if in == nil {
		return nil
	}
	out := new(CapabilityBundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityBundleSpec) DeepCopyInto(out *CapabilityBundleSpec) {
	*out = *in
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(EgressPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Harness != nil {
		in, out := &in.Harness, &out.Harness
		*out = new(HarnessPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(GovernanceBoundary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityBundleSpec.
func (in *CapabilityBundleSpec) DeepCopy() *CapabilityBundleSpec {
	if in == nil {
		return nil
	}
	out := new(CapabilityBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandPolicyRule) DeepCopyInto(out *CommandPolicyRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandPolicyRule.
func (in *CommandPolicyRule) DeepCopy() *CommandPolicyRule {
	if in == nil {
		return nil
	}
	out := new(CommandPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressPolicy) DeepCopyInto(out *EgressPolicy) {
	*out = *in
	if in.Agentgateway != nil {
		in, out := &in.Agentgateway, &out.Agentgateway
		*out = make(map[string]AgentgatewayBackendPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressPolicy.
func (in *EgressPolicy) DeepCopy() *EgressPolicy {
	if in == nil {
		return nil
	}
	out := new(EgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernanceBoundary) DeepCopyInto(out *GovernanceBoundary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernanceBoundary.
func (in *GovernanceBoundary) DeepCopy() *GovernanceBoundary {
	if in == nil {
		return nil
	}
	out := new(GovernanceBoundary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernanceIdentity) DeepCopyInto(out *GovernanceIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernanceIdentity.
func (in *GovernanceIdentity) DeepCopy() *GovernanceIdentity {
	if in == nil {
		return nil
	}
	out := new(GovernanceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessPolicy) DeepCopyInto(out *HarnessPolicy) {
	*out = *in
	if in.CommandPolicy != nil {
		in, out := &in.CommandPolicy, &out.CommandPolicy
		*out = make([]CommandPolicyRule, len(*in))
		copy(*out, *in)
	}
	if in.ValidationRules != nil {
		in, out := &in.ValidationRules, &out.ValidationRules
		*out = make([]ValidationRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessPolicy.
func (in *HarnessPolicy) DeepCopy() *HarnessPolicy {
	if in == nil {
		return nil
	}
	out := new(HarnessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedCapabilityBundle) DeepCopyInto(out *ResolvedCapabilityBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedCapabilityBundle.
func (in *ResolvedCapabilityBundle) DeepCopy() *ResolvedCapabilityBundle {
	if in == nil {
		return nil
	}
	out := new(ResolvedCapabilityBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAccessRequest) DeepCopyInto(out *SandboxAccessRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAccessRequest.
func (in *SandboxAccessRequest) DeepCopy() *SandboxAccessRequest {
	if in == nil {
		return nil
	}
	out := new(SandboxAccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAccessRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAccessRequestList) DeepCopyInto(out *SandboxAccessRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAccessRequestList.
func (in *SandboxAccessRequestList) DeepCopy() *SandboxAccessRequestList {
	if in == nil {
		return nil
	}
	out := new(SandboxAccessRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAccessRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAccessRequestSpec) DeepCopyInto(out *SandboxAccessRequestSpec) {
	*out = *in
	out.AssignmentRef = in.AssignmentRef
	out.Requester = in.Requester
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAccessRequestSpec.
func (in *SandboxAccessRequestSpec) DeepCopy() *SandboxAccessRequestSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxAccessRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAccessRequestStatus) DeepCopyInto(out *SandboxAccessRequestStatus) {
	*out = *in
	if in.Approver != nil {
		in, out := &in.Approver, &out.Approver
		*out = new(GovernanceIdentity)
		**out = **in
	}
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAccessRequestStatus.
func (in *SandboxAccessRequestStatus) DeepCopy() *SandboxAccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxAccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAssignment) DeepCopyInto(out *SandboxAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAssignment.
func (in *SandboxAssignment) DeepCopy() *SandboxAssignment {
	if in == nil {
		return nil
	}
	out := new(SandboxAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAssignmentList) DeepCopyInto(out *SandboxAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAssignmentList.
func (in *SandboxAssignmentList) DeepCopy() *SandboxAssignmentList {
	if in == nil {
		return nil
	}
	out := new(SandboxAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAssignmentSpec) DeepCopyInto(out *SandboxAssignmentSpec) {
	*out = *in
	out.CapabilityBundleRef = in.CapabilityBundleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAssignmentSpec.
func (in *SandboxAssignmentSpec) DeepCopy() *SandboxAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAssignmentStatus) DeepCopyInto(out *SandboxAssignmentStatus) {
	*out = *in
	if in.WorkloadRef != nil {
		in, out := &in.WorkloadRef, &out.WorkloadRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(ObjectReference)
		**out = **in
	}
	if in.ResolvedCapabilityBundle != nil {
		in, out := &in.ResolvedCapabilityBundle, &out.ResolvedCapabilityBundle
		*out = new(ResolvedCapabilityBundle)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAssignmentStatus.
func (in *SandboxAssignmentStatus) DeepCopy() *SandboxAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxTemplate) DeepCopyInto(out *SandboxTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxTemplate.
func (in *SandboxTemplate) DeepCopy() *SandboxTemplate {
	if in == nil {
		return nil
	}
	out := new(SandboxTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxTemplateList) DeepCopyInto(out *SandboxTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxTemplateList.
func (in *SandboxTemplateList) DeepCopy() *SandboxTemplateList {
	if in == nil {
		return nil
	}
	out := new(SandboxTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxTemplateResources) DeepCopyInto(out *SandboxTemplateResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxTemplateResources.
func (in *SandboxTemplateResources) DeepCopy() *SandboxTemplateResources {
	if in == nil {
		return nil
	}
	out := new(SandboxTemplateResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxTemplateSpec) DeepCopyInto(out *SandboxTemplateSpec) {
	*out = *in
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.CapabilityBundleRef = in.CapabilityBundleRef
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxTemplateSpec.
func (in *SandboxTemplateSpec) DeepCopy() *SandboxTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxTenantPolicy) DeepCopyInto(out *SandboxTenantPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *SandboxTenantPolicy) DeepCopy() *SandboxTenantPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxTenantPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxTenantPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxTenantPolicyList) DeepCopyInto(out *SandboxTenantPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxTenantPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxTenantPolicyList) DeepCopy() *SandboxTenantPolicyList {
	if in == nil {
		return nil
	}
	out := new(SandboxTenantPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxTenantPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxTenantPolicySpec) DeepCopyInto(out *SandboxTenantPolicySpec) {
	*out = *in
	if in.AllowedCapabilityBundles != nil {
		in, out := &in.AllowedCapabilityBundles, &out.AllowedCapabilityBundles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedCapabilityBundlePrefixes != nil {
		in, out := &in.AllowedCapabilityBundlePrefixes, &out.AllowedCapabilityBundlePrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SandboxTenantPolicySpec) DeepCopy() *SandboxTenantPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SandboxTenantPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressEvent) DeepCopyInto(out *SandboxEgressEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *SandboxCredentialEvent) DeepCopyInto(out *SandboxCredentialEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *SandboxCredentialEvent) DeepCopy() *SandboxCredentialEvent {
	if in == nil {
		return nil
	}
	out := new(SandboxCredentialEvent)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxCredentialEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxCredentialEventList) DeepCopyInto(out *SandboxCredentialEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxCredentialEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxCredentialEventList) DeepCopy() *SandboxCredentialEventList {
	if in == nil {
		return nil
	}
	out := new(SandboxCredentialEventList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxCredentialEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxCredentialEventSpec) DeepCopyInto(out *SandboxCredentialEventSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	out.AssignmentRef = in.AssignmentRef
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

func (in *SandboxCredentialEventSpec) DeepCopy() *SandboxCredentialEventSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxCredentialEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressEvent.
func (in *SandboxEgressEvent) DeepCopy() *SandboxEgressEvent {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxEgressEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressEventList) DeepCopyInto(out *SandboxEgressEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxEgressEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressEventList.
func (in *SandboxEgressEventList) DeepCopy() *SandboxEgressEventList {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxEgressEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressEventSpec) DeepCopyInto(out *SandboxEgressEventSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	out.AssignmentRef = in.AssignmentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressEventSpec.
func (in *SandboxEgressEventSpec) DeepCopy() *SandboxEgressEventSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressEventSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxValidationCommandResult) DeepCopyInto(out *SandboxValidationCommandResult) {
	*out = *in
}

func (in *SandboxValidationCommandResult) DeepCopy() *SandboxValidationCommandResult {
	if in == nil {
		return nil
	}
	out := new(SandboxValidationCommandResult)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxValidationRun) DeepCopyInto(out *SandboxValidationRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SandboxValidationRun) DeepCopy() *SandboxValidationRun {
	if in == nil {
		return nil
	}
	out := new(SandboxValidationRun)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxValidationRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxValidationRunList) DeepCopyInto(out *SandboxValidationRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxValidationRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxValidationRunList) DeepCopy() *SandboxValidationRunList {
	if in == nil {
		return nil
	}
	out := new(SandboxValidationRunList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxValidationRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxValidationRunSpec) DeepCopyInto(out *SandboxValidationRunSpec) {
	*out = *in
	if in.ChangedPaths != nil {
		in, out := &in.ChangedPaths, &out.ChangedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SelectedCommands != nil {
		in, out := &in.SelectedCommands, &out.SelectedCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AssignmentRef = in.AssignmentRef
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

func (in *SandboxValidationRunSpec) DeepCopy() *SandboxValidationRunSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxValidationRunSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxValidationRunStatus) DeepCopyInto(out *SandboxValidationRunStatus) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]SandboxValidationCommandResult, len(*in))
		copy(*out, *in)
	}
}

func (in *SandboxValidationRunStatus) DeepCopy() *SandboxValidationRunStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxValidationRunStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ValidationRule) DeepCopyInto(out *ValidationRule) {
	*out = *in
}

func (in *ValidationRule) DeepCopy() *ValidationRule {
	if in == nil {
		return nil
	}
	out := new(ValidationRule)
	in.DeepCopyInto(out)
	return out
}
